USE Manufacturing;
GO

ALTER TABLE Customer WITH CHECK
ADD CONSTRAINT FK_Zipcode FOREIGN KEY(Zipcode) REFERENCES ZipCode(ZipCode)
ON UPDATE CASCADE
GO


ALTER TABLE Manufacturer WITH CHECK
ADD CONSTRAINT MfgZipCode FOREIGN KEY (MfgZipCode) REFERENCES ZipCode(ZipCode)
ON UPDATE CASCADE
GO

ALTER TABLE Orders WITH CHECK
ADD CONSTRAINT FK_CustomerID FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID)
ON UPDATE CASCADE
GO

ALTER TABLE OrderDetails WITH CHECK
ADD CONSTRAINT FK_OrderID FOREIGN KEY (OrderID) REFERENCES Orders(ID)
ON UPDATE CASCADE
GO

ALTER TABLE Part WITH CHECK
ADD CONSTRAINT FK_MfgID FOREIGN KEY (MfgID) REFERENCES Manufacturer(ManufacturerID)
ON UPDATE CASCADE
GO




ALTER TABLE Part WITH CHECK
ADD CONSTRAINT FK_MachineNumber FOREIGN KEY (MachineNumber) REFERENCES Machines(MachineNumber)
ON UPDATE CASCADE
GO

ALTER TABLE OrderDetails WITH CHECK
ADD CONSTRAINT FK_PartNumber FOREIGN KEY (PartNumber) REFERENCES Part(PartNumber)
ON UPDATE NO ACTION
GO
